CREATE TABLE IF NOT EXISTS silver_users (
    user_id               BIGINT PRIMARY KEY,
    email                 TEXT,
    phone                 TEXT,
    role                  TEXT,
    is_active             BOOLEAN,
    customer_id           TEXT,
    subscription_id       BIGINT,
    subscription_start    TIMESTAMPTZ,
    subscription_renewal  TIMESTAMPTZ,
    subscription_end      TIMESTAMPTZ,
    cancel_subscription   BOOLEAN,
    free_subscriptions    INT,
    lang                  TEXT,
    profile               JSONB,
    credits               REAL,
    owner_id              BIGINT,
    cdn_quota             BIGINT,
    encoder_quota         BIGINT,
    cdn_usage             BIGINT,
    access_id             BIGINT,
    created_at            TIMESTAMPTZ,
    updated_at            TIMESTAMPTZ
);