CREATE TABLE IF NOT EXISTS silver_actions (
    action_id         BIGINT PRIMARY KEY,
    created_at        TIMESTAMPTZ,
    user_id           BIGINT,
    ad_id             BIGINT,
    content_id        BIGINT,
    page_id           BIGINT,
    subscription_id   BIGINT,
    reseller_id       BIGINT,
    profile_id        BIGINT,
    library_id        BIGINT,
    program           TEXT,
    device_id         TEXT,
    periods           INTEGER,
    action_type       TEXT,
    label             TEXT,
    country           TEXT,
    os                TEXT,
    os_version        TEXT,
    browser           TEXT,
    browser_version   TEXT,
    system_lang       TEXT,
    lang              TEXT,
    isp               TEXT,
    state             TEXT,
    city              TEXT,
    user_hash         TEXT,
    metadata          JSONB
);
