BEGIN;

DELETE FROM silver_actions;

INSERT INTO silver_actions (
    action_id,
    created_at,
    user_id,
    ad_id,
    content_id,
    page_id,
    subscription_id,
    reseller_id,
    profile_id,
    library_id,
    program,
    device_id,
    periods,
    action_type,
    label,
    country,
    os,
    os_version,
    browser,
    browser_version,
    system_lang,
    lang,
    isp,
    state,
    city,
    user_hash,
    metadata
)
SELECT
    id,
    created_at,
    user_id,
    ad_id,
    content_id,
    page_id,
    subscription_id,
    reseller_id,
    profile_id,
    library_id,
    program,
    device_id,
    periods,
    type,
    label,
    country,
    os,
    os_version,
    browser,
    browser_version,
    system_lang,
    lang,
    isp,
    state,
    city,
    user_hash,
    metadata
FROM dblink(
    'host=169.255.179.24 port=5432 dbname=snrt_stats user=snrt_readonly password=6AOd3Dm2',
    'SELECT
         id,
         created_at,
         user_id,
         ad_id,
         content_id,
         page_id,
         subscription_id,
         reseller_id,
         profile_id,
         library_id,
         program,
         device_id,
         periods,
         type,
         label,
         country,
         os,
         os_version,
         browser,
         browser_version,
         system_lang,
         lang,
         isp,
         state,
         city,
         user_hash,
         metadata
     FROM actions'
) AS t(
    id BIGINT,
    created_at TIMESTAMPTZ,
    user_id BIGINT,
    ad_id BIGINT,
    content_id BIGINT,
    page_id BIGINT,
    subscription_id BIGINT,
    reseller_id BIGINT,
    profile_id BIGINT,
    library_id BIGINT,
    program TEXT,
    device_id TEXT,
    periods INTEGER,
    type TEXT,
    label TEXT,
    country TEXT,
    os TEXT,
    os_version TEXT,
    browser TEXT,
    browser_version TEXT,
    system_lang TEXT,
    lang TEXT,
    isp TEXT,
    state TEXT,
    city TEXT,
    user_hash TEXT,
    metadata JSONB
);

COMMIT;
